In [2]:
import pandas as pd

In [3]:
cubo = pd.read_excel(r"C:\Users\fdavila\OneDrive - Farmacorp S.A\Escritorio\ANALISIS -CORRELACION\data\cubo_1.xlsx", 
                    sheet_name = 'cat4',
                    skiprows=4
                    )

In [4]:
clusters = pd.read_excel(r"C:\Users\fdavila\OneDrive - Farmacorp S.A\Escritorio\ANALISIS -CORRELACION\data\clusters_bdg.xlsx")

In [5]:
clusters_fc = clusters[clusters['UNE']=='FARMACORP']

In [6]:
#base = pd.read_csv("Ventasxfacturas.csv")
#base.to_parquet("Ventasxfacturas.parquet", engine="fastparquet", index=False)

In [7]:
ventasxfact = pd.read_parquet(r"C:\Users\fdavila\OneDrive - Farmacorp S.A\Escritorio\ANALISIS -CORRELACION\data\Ventasxfacturas.parquet")

In [8]:
cubo['COD_ARTICULO'] = cubo['COD_ARTICULO'].astype(str)
ventasxfact['COD_ARTICULO'] = ventasxfact['COD_ARTICULO'].astype(str)

In [9]:
cubo_fc = pd.merge(
    cubo,
    clusters_fc,
    left_on='COD_BODEGA',
    right_on='BODEGA'
)

In [10]:
cubo_fc

,CAT 4,COD_ARTICULO,COD_BODEGA,Venta neta,Unidades,BODEGA,UNE,BODEGA2,CIUDAD,REGION,FORMATO,NSE,CLUSTER
0,AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO,7754734000432,B112,927.00,6,B112,FARMACORP,SC-05 CANOTO-Esq.MEXICO,Santa Cruz,LLANO,GRANDE,B,GRANDE-B
1,AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO,7754734000432,B113,154.50,1,B113,FARMACORP,SC-16 VILLA 1ro.DE MAYO Esq.CALLE 8,Santa Cruz,LLANO,TRADICIONAL,C,TRADICIONAL-C
2,AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO,7754734000432,B116,463.50,3,B116,FARMACORP,SC-20 VIRGEN DE COTOCA Esq.2doAnill,Santa Cruz,LLANO,MEDIANA,B,MEDIANA-B
3,AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO,7754734000432,B195,154.50,1,B195,FARMACORP,"SC-153 NOEL KEMPFF M. 3ER A, INT (ONCOLOGICO)",Santa Cruz,LLANO,MEDIANA,B,MEDIANA-B
4,AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO,7754734000432,B199,618.00,4,B199,FARMACORP,SC-156 AV. 3ER A. EXT (Z/CONAVI HOSP OBRERO),Santa Cruz,LLANO,TRADICIONAL,C,TRADICIONAL-C
...,...,...,...,...,...,...,...,...,...,...,...,...,...
550557,YODO,370191,B703,117.50,15,B703,FARMACORP,BE-145 AV BOLIVAR ESQ ADOLFO VELASCO,Beni,LLANO,MEDIANA,B,MEDIANA-B
550558,YODO,370191,B801,102.20,14,B801,FARMACORP,PA-83 AV.09 DE FEBRERO (DIAG C/BENI),Pando,LLANO,PERMITIDO,B,PERMITIDO-B
550559,YODO,370191,B802,70.98,9,B802,FARMACORP,PA - AV. ENRIQUE FERNANDEZ C.(P. G.BUSCH),Pando,LLANO,GRANDE,B,GRANDE-B
550560,YODO,370191,B803,352.69,45,B803,FARMACORP,PA - AV. TAHUAMANU ESQ. 9 DE FEBRERO,Pando,LLANO,GRANDE,B,GRANDE-B
550561,YODO,370191,B901,320.62,41,B901,FARMACORP,PO-115 AV. LITORAL ESQ. CHAYANTA,Potosi,ALTIPLANO,MEDIANA,B,MEDIANA-B

In [11]:
cubo_cat4 = cubo_fc[['COD_ARTICULO', 'CAT 4']].drop_duplicates()

In [12]:
ventasxfact = pd.merge(
  ventasxfact,
  clusters_fc,
  left_on='COD_BODEGA',
  right_on='BODEGA'
 )

In [13]:
# filtering only SKUs on FARMACORP
ventas_farmacia = pd.merge(cubo_cat4,
                            ventasxfact,
                            on='COD_ARTICULO',
                            how='inner'
                            )

In [14]:
ventas_farmacia

,COD_ARTICULO,CAT 4,FECHA,COD_BODEGA,NRO_FACTURAS,# Sell-OUT,Ventas,BODEGA,UNE,BODEGA2,CIUDAD,REGION,FORMATO,NSE,CLUSTER
0,7754734000432,AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO,2025-08-11 00:00:00.000,B112,7080220S12,3.0,463.5,B112,FARMACORP,SC-05 CANOTO-Esq.MEXICO,Santa Cruz,LLANO,GRANDE,B,GRANDE-B
1,7754734000432,AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO,2025-08-22 00:00:00.000,B112,7088314S12,1.0,154.5,B112,FARMACORP,SC-05 CANOTO-Esq.MEXICO,Santa Cruz,LLANO,GRANDE,B,GRANDE-B
2,7754734000432,AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO,2025-08-26 00:00:00.000,B199,535206SCL,5.0,772.5,B199,FARMACORP,SC-156 AV. 3ER A. EXT (Z/CONAVI HOSP OBRERO),Santa Cruz,LLANO,TRADICIONAL,C,TRADICIONAL-C
3,7754734000432,AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO,2025-08-28 00:00:00.000,B195,474316SCD,1.0,154.5,B195,FARMACORP,"SC-153 NOEL KEMPFF M. 3ER A, INT (ONCOLOGICO)",Santa Cruz,LLANO,MEDIANA,B,MEDIANA-B
4,7754734000432,AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO,2025-08-30 00:00:00.000,B112,7093588S12,1.0,154.5,B112,FARMACORP,SC-05 CANOTO-Esq.MEXICO,Santa Cruz,LLANO,GRANDE,B,GRANDE-B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5847968,370191,YODO,2025-10-31 00:00:00.000,B304,1254307L4,1.0,8.1,B304,FARMACORP,LP-63 AV.G.LANZA Esq. C/9 (ACHUMANI),La paz,ALTIPLANO,MEDIANA,A,MEDIANA-A
5847969,370191,YODO,2025-10-31 00:00:00.000,B323,285901L23,1.0,8.1,B323,FARMACORP,LP - AV. J.AGUIRRE ESQ C/5 (LOS PINOS),La paz,ALTIPLANO,PEQUENA,B,PEQUENA-B
5847970,370191,YODO,2025-10-31 00:00:00.000,B402,2874837T2,1.0,8.1,B402,FARMACORP,TJ-46 AV. JAIME PAZ Esq.EULOGIO RUIZ,Tarija,VALLE,MEDIANA,B,MEDIANA-B
5847971,370191,YODO,2025-10-31 00:00:00.000,B701,2117645B1,1.0,8.1,B701,FARMACORP,BE-75 C/J.SIERRA Pza.BALLIVIAN(TRINIDAD),Beni,LLANO,GRANDE,B,GRANDE-B
5847972,370191,YODO,2025-10-31 00:00:00.000,B802,270165P2,1.0,8.1,B802,FARMACORP,PA - AV. ENRIQUE FERNANDEZ C.(P. G.BUSCH),Pando,LLANO,GRANDE,B,GRANDE-B

### SUPPORT A

In [15]:
ventasxbdg = ventas_farmacia.groupby('COD_BODEGA').agg({'NRO_FACTURAS':'nunique'}).reset_index()

In [16]:
ventasxbdg

    COD_BODEGA  NRO_FACTURAS
0         B101         23689
1         B102         27479
2         B104         28143
3         B108          9527
4         B109         20018
..         ...           ...
184       B703         21183
185       B801          9803
186       B802         12178
187       B803         27257
188       B901         23621

[189 rows x 2 columns]

In [17]:
ventasxcat = ventas_farmacia.groupby(['CAT 4', 'COD_BODEGA']).agg({'NRO_FACTURAS':'nunique'}).reset_index()

In [18]:
ventas_cat_bdg = pd.merge(
    ventasxcat,
    ventasxbdg,
    on='COD_BODEGA',
    suffixes=('_CAT4', '_TOTAL_BDG')
)

In [19]:
ventas_cat_bdg

,CAT 4,COD_BODEGA,NRO_FACTURAS_CAT4,NRO_FACTURAS_TOTAL_BDG
0,AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO,B112,7,39375
1,AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO,B113,1,30869
2,AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO,B116,1,20634
3,AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO,B195,2,9822
4,AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO,B199,3,16602
...,...,...,...,...
48720,YODO,B703,20,21183
48721,YODO,B801,16,9803
48722,YODO,B802,12,12178
48723,YODO,B803,43,27257
48724,YODO,B901,34,23621

In [20]:
ventas_cat_bdg['support_cat4'] = ventas_cat_bdg['NRO_FACTURAS_CAT4'] / ventas_cat_bdg['NRO_FACTURAS_TOTAL_BDG']

In [21]:
ventas_cat_bdg = ventas_cat_bdg.sort_values(by=['COD_BODEGA', 'support_cat4'], ascending=[True, False])

In [22]:
ventas_cat_bdg = ventas_cat_bdg.groupby('COD_BODEGA').head(50)

In [23]:
ventas_cat_bdg

,CAT 4,COD_BODEGA,NRO_FACTURAS_CAT4,NRO_FACTURAS_TOTAL_BDG,support_cat4
13555,ANTIRREUMATICOS NO ESTEROIDEOS,B101,3435,23689,0.145004
1720,ANALGESICOS NO NARCOTICOS ANTIPIRETICOS.,B101,2908,23689,0.122757
9107,ANTIGRIPALES EXC.ANTIINFARINGITIS,B101,2620,23689,0.110600
26843,HIPNOTICOS Y SEDANTES,B101,1533,23689,0.064714
3412,ANTIACIDOS SOLOS,B101,1052,23689,0.044409
...,...,...,...,...,...
21043,CORTICOSTEROIDES TOPICOS ASOCIACIONES,B901,189,23621,0.008001
23141,DIURETICOS,B901,175,23621,0.007409
45996,SUPLEMENTOS DIETARIO ALIMENTICIO,B901,168,23621,0.007112
4955,ANTIBACTERIANOS ASOCIACION TRIMETOPRIMA Y SIMI...,B901,167,23621,0.007070
35036,OTRAS VITAMINAS SOLAS Y COMBINADAS,B901,159,23621,0.006731

### SUPPORT AyB

In [24]:
# selfmerge forfinding pairs of CAT 4 on same invoice
pairs_factura = pd.merge(
    ventas_farmacia,
    ventas_farmacia,
    on=["NRO_FACTURAS", "COD_BODEGA"],
    suffixes=("_A", "_B")
)

# filtering combinations to avoid duplicates
pairs_factura = pairs_factura[pairs_factura["CAT 4_A"] != pairs_factura["CAT 4_B"]]

# keeping only one order of each pair
pairs_factura = pairs_factura[pairs_factura["CAT 4_A"] > pairs_factura["CAT 4_B"]]

In [25]:
pairs_factura[['CAT 4_A', 'CAT 4_B', 'NRO_FACTURAS', 'COD_BODEGA']].shape

(3782749, 4)

In [26]:
ventasABxbdg = pairs_factura.groupby(['CAT 4_A', 'CAT 4_B', 'COD_BODEGA']).agg({'NRO_FACTURAS':'nunique'}).reset_index()

In [27]:
ventasABxbdg.sort_values(by=['COD_BODEGA', 'NRO_FACTURAS'], ascending=[True, False])

,CAT 4_A,CAT 4_B,COD_BODEGA,NRO_FACTURAS
112585,ANTIRREUMATICOS NO ESTEROIDEOS,ANALGESICOS NO NARCOTICOS ANTIPIRETICOS.,B101,373
118552,ANTIRREUMATICOS NO ESTEROIDEOS,ANTIGRIPALES EXC.ANTIINFARINGITIS,B101,361
56280,ANTIGRIPALES EXC.ANTIINFARINGITIS,ANALGESICOS NO NARCOTICOS ANTIPIRETICOS.,B101,269
242787,DESCONGESTIONANTES FARINGITICOS,ANTIGRIPALES EXC.ANTIINFARINGITIS,B101,209
115277,ANTIRREUMATICOS NO ESTEROIDEOS,ANTIBACTERIANOS PENICILINAS AMPLIO ESPECTRO,B101,197
...,...,...,...,...
786360,YODO,PRODUCTOS PARA TRATAR EL PRURITO-PICAZON EXZEMAS,B901,1
786420,YODO,RESTAURADOR ELECTROLITOS ORAL,B901,1
786510,YODO,SUPLEMENTOS CON MAGNESIO,B901,1
786517,YODO,SUPLEMENTOS DIETARIO ALIMENTICIO,B901,1
786593,YODO,VITAMINA C,B901,1

In [28]:
ventasxpairs = pd.merge(
    ventasABxbdg,
    ventasxbdg,
    on='COD_BODEGA',
    suffixes=('_PAIR', '_TOTAL_BDG')
)

In [29]:
ventasxpairs['support_AB'] = (ventasxpairs['NRO_FACTURAS_PAIR'] / ventasxpairs['NRO_FACTURAS_TOTAL_BDG']).round(8)

In [30]:
ventasxpairs.sort_values(by=['COD_BODEGA', 'NRO_FACTURAS_PAIR'], ascending=[True, False])

,CAT 4_A,CAT 4_B,COD_BODEGA,NRO_FACTURAS_PAIR,NRO_FACTURAS_TOTAL_BDG,support_AB
112585,ANTIRREUMATICOS NO ESTEROIDEOS,ANALGESICOS NO NARCOTICOS ANTIPIRETICOS.,B101,373,23689,0.015746
118552,ANTIRREUMATICOS NO ESTEROIDEOS,ANTIGRIPALES EXC.ANTIINFARINGITIS,B101,361,23689,0.015239
56280,ANTIGRIPALES EXC.ANTIINFARINGITIS,ANALGESICOS NO NARCOTICOS ANTIPIRETICOS.,B101,269,23689,0.011355
242787,DESCONGESTIONANTES FARINGITICOS,ANTIGRIPALES EXC.ANTIINFARINGITIS,B101,209,23689,0.008823
115277,ANTIRREUMATICOS NO ESTEROIDEOS,ANTIBACTERIANOS PENICILINAS AMPLIO ESPECTRO,B101,197,23689,0.008316
...,...,...,...,...,...,...
786360,YODO,PRODUCTOS PARA TRATAR EL PRURITO-PICAZON EXZEMAS,B901,1,23621,0.000042
786420,YODO,RESTAURADOR ELECTROLITOS ORAL,B901,1,23621,0.000042
786510,YODO,SUPLEMENTOS CON MAGNESIO,B901,1,23621,0.000042
786517,YODO,SUPLEMENTOS DIETARIO ALIMENTICIO,B901,1,23621,0.000042
786593,YODO,VITAMINA C,B901,1,23621,0.000042

In [31]:
ventas_cat_bdg_pairs = pd.merge(
    ventas_cat_bdg[['CAT 4', 'COD_BODEGA', 'NRO_FACTURAS_CAT4', 'support_cat4']],
    ventasxpairs,
    left_on=['CAT 4', 'COD_BODEGA'],
    right_on=['CAT 4_A', 'COD_BODEGA'],
    #how='left'
)

In [32]:
ventas_pairs = pd.merge(
    ventas_cat_bdg_pairs[['COD_BODEGA', 'NRO_FACTURAS_CAT4', 
                            'support_cat4', 'CAT 4_A','CAT 4_B', 'NRO_FACTURAS_PAIR', 
                            'NRO_FACTURAS_TOTAL_BDG', 'support_AB']],
    ventas_cat_bdg[['CAT 4', 'COD_BODEGA', 'support_cat4', 'NRO_FACTURAS_CAT4']],
    left_on=['CAT 4_B', 'COD_BODEGA'],
    right_on=['CAT 4', 'COD_BODEGA'],
    #how='left',
    suffixes=['_A', '_B']
)

In [33]:
ventas_pairs = ventas_pairs[[
    'COD_BODEGA', 'CAT 4_A', 'CAT 4_B', 
    'NRO_FACTURAS_CAT4_A', 'NRO_FACTURAS_CAT4_B', 'NRO_FACTURAS_PAIR', 'NRO_FACTURAS_TOTAL_BDG', 
    'support_cat4_A', 'support_cat4_B', 'support_AB',
    
]]

In [34]:
ventas_pairs['confidence_AB_A'] = (ventas_pairs['support_AB'] / ventas_pairs['support_cat4_A']).round(8)

In [35]:
ventas_pairs['lift_ABA_B'] = (ventas_pairs['confidence_AB_A'] / ventas_pairs['support_cat4_B']).round(8)

In [36]:
ventas_pairs = ventas_pairs.sort_values(by=['COD_BODEGA', 'support_cat4_A', 'confidence_AB_A'], ascending=[True,False, False])

In [37]:
ventasxcat = ventas_farmacia.groupby(['CAT 4', 'COD_BODEGA']).agg({'Ventas':'sum'}).reset_index()

In [38]:
ventasxcat

                                                   CAT 4 COD_BODEGA   Ventas
0      AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO       B112  1699.50
1      AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO       B113   154.50
2      AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO       B116   463.50
3      AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO       B195   309.00
4      AGENTE DEXINTOXICANTE TRATAMIENTO ANTI-NEOPLASICO       B199  1390.50
...                                                  ...        ...      ...
48720                                               YODO       B703   163.51
48721                                               YODO       B801   160.60
48722                                               YODO       B802    90.99
48723                                               YODO       B803   332.11
48724                                               YODO       B901   271.28

[48725 rows x 3 columns]

In [39]:
ventas_pairs = pd.merge(
    ventas_pairs,
    ventasxcat,
    left_on=['CAT 4_B', 'COD_BODEGA'],
    right_on=['CAT 4', 'COD_BODEGA'],
    how='left'
)

In [40]:
ventas_pairs_fc = ventas_pairs[[
    'COD_BODEGA', 'CAT 4_A', 'CAT 4_B', 
    'NRO_FACTURAS_CAT4_A','NRO_FACTURAS_CAT4_B', 'NRO_FACTURAS_PAIR', 'NRO_FACTURAS_TOTAL_BDG',
    'support_cat4_A', 'support_cat4_B', 'support_AB', 'confidence_AB_A','lift_ABA_B', 'Ventas']].copy()

In [41]:
ventas_pairs_fc

,COD_BODEGA,CAT 4_A,CAT 4_B,NRO_FACTURAS_CAT4_A,NRO_FACTURAS_CAT4_B,NRO_FACTURAS_PAIR,NRO_FACTURAS_TOTAL_BDG,support_cat4_A,support_cat4_B,support_AB,confidence_AB_A,lift_ABA_B,Ventas
0,B101,ANTIRREUMATICOS NO ESTEROIDEOS,ANALGESICOS NO NARCOTICOS ANTIPIRETICOS.,3435,2908,373,23689,0.145004,0.122757,0.015746,0.108588,0.884574,47325.03
1,B101,ANTIRREUMATICOS NO ESTEROIDEOS,ANTIGRIPALES EXC.ANTIINFARINGITIS,3435,2620,361,23689,0.145004,0.110600,0.015239,0.105095,0.950224,51735.93
2,B101,ANTIRREUMATICOS NO ESTEROIDEOS,ANTIBACTERIANOS PENICILINAS AMPLIO ESPECTRO,3435,593,197,23689,0.145004,0.025033,0.008316,0.057351,2.291035,21954.81
3,B101,ANTIRREUMATICOS NO ESTEROIDEOS,ANTIHISTAMINICOS-ANTIALERGICOS,3435,655,86,23689,0.145004,0.027650,0.003630,0.025036,0.905477,15373.60
4,B101,ANTIRREUMATICOS NO ESTEROIDEOS,ANTIACIDOS SOLOS,3435,1052,83,23689,0.145004,0.044409,0.003504,0.024163,0.544105,11203.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
183572,B901,OTRAS VITAMINAS SOLAS Y COMBINADAS,ANALGESICOS NARCOTICOS,159,281,1,23621,0.006731,0.011896,0.000042,0.006290,0.528742,11992.01
183573,B901,OTRAS VITAMINAS SOLAS Y COMBINADAS,ANGIOTENSINA-II ANTAGONISTAS SOLO,159,275,1,23621,0.006731,0.011642,0.000042,0.006290,0.540278,12935.45
183574,B901,OTRAS VITAMINAS SOLAS Y COMBINADAS,ANTIBACTERIANOS PENICILINAS MEDIO Y REDUCIDO E...,159,194,1,23621,0.006731,0.008213,0.000042,0.006290,0.765859,9776.75
183575,B901,OTRAS VITAMINAS SOLAS Y COMBINADAS,ANTIESPASMODICOS,159,199,1,23621,0.006731,0.008425,0.000042,0.006290,0.746616,5131.57
183576,B901,OTRAS VITAMINAS SOLAS Y COMBINADAS,HORMONAS ANTICONCEPTIVAS SISTEMICO,159,396,1,23621,0.006731,0.016765,0.000042,0.006290,0.375193,24796.21

In [42]:
ventas_pairs_fc.to_excel(r"C:\Users\fdavila\OneDrive - Farmacorp S.A\Escritorio\ANALISIS -CORRELACION\output\support_analysis_bdg_test.xlsx", index=False)